### ISSUE TITLE
duplicate exponent in ridge term

### ISSUE THREAD

**Issue by WSDeWitt** [harrispopgen/mushi#58]
The generalized Tikhonov term for demography seems to have retained an exponent 2 from a previous implementation. This is a bug because the matrix product by itself results in squared entries.
https://github.com/harrispopgen/mushi/blob/31d71a960a9042fa26a9acd09f1e39ff76b02540/mushi/ksfs.py#L297-L298

**Comment by kamdh** [comment]
Looks like a bug
