### ISSUE TITLE
alternatives to prox-tv dependency

### ISSUE THREAD

**Issue by WSDeWitt** [harrispopgen/mushi#59]
Prox-tv is great, but seems not to be under active development (albarji/proxTV#59), so it might be good to think about alternatives. As is, we're stuck at Python3.7 due to the lack of Python3.8 wheels for prox-tv albarji/proxTV#56.

**Comment by kamdh** [comment]
Could fork and regenerate py3.8 compatible I guess...

**Comment by kamdh** [comment]
Last I checked proxtv was the best option for this kind of package

**Comment by WSDeWitt** [comment]
The 3.7 constraint is now creating friction in adoption of `mushi.optimization` in another project that requires 3.8. I plan to (at some point) write a JAX implementation of algorithm 1 from [this paper](https://icml.cc/2011/papers/226_icmlpaper.pdf) (which is cited in the prox-tv docs), and compare performance to prox-tv.

**Comment by WSDeWitt** [comment]
Reopening because, although this works for pip install from the GitHub package, a simple `pip install mushi` still doesn't work due to pypi disallowing direct git dependencies.
