### ISSUE TITLE
Tiny bug in pipeline

### ISSUE THREAD

**Issue by terhorst** [harrispopgen/mushi#61]
Hi there,

I encountered a small bug when running your 1kg pipeline. The offending line is:

https://github.com/harrispopgen/mushi/blob/a20069339ecb8c730bddb4939b252f0fd63820ce/1KG/SConstruct#L83-L84

When I run this command, it produces an empty `.bed` file, resulting in a fatal error soon after. I believe the issue is that `egrep` on my machine defaults to POSIX regexps, which don't match tabs as `\t`. I fixed it by switching to PCRE via `grep -P`. (I suspect this is the default behavior of `egrep` on whatever your development platform is.)
I'm on a recent version of Ubuntu. Cheers,

Jonathan

**Comment by WSDeWitt** [comment]
Hi 😃, thanks for bringing this to our attention! We're planning several revisions of our pipeline in the near future, so we'll be sure to include this fix.
