### ISSUE TITLE
Step-by-step guide from mutyper

### ISSUE THREAD

**Issue by RenzoTale88** [harrispopgen/mushi#73]
Hi @WSDeWitt 
It might be a silly question, but I was wondering if there is somewhere a step-by-step guide to use mushi for demographic inference starting from outputs from mutyper.
I've tried to follow the read the docs, but I find it slightly tricky to follow starting from actual data.
Thank you in advance

Andrea

**Comment by WSDeWitt** [comment]
Hi Andrea,

In the QuickStart page there is an example for how to instantiate a `kSFS` object from a mutyper output file: https://harrispopgen.github.io/mushi/notebooks/quickstart.html#2.-From-a-tsv-file

Demographic inference can then be done by calling a method on this object, as in this example: https://harrispopgen.github.io/mushi/notebooks/quickstart.html#Demographic-inference

There are a number of other options and parameters available for this demography inference method, detailed in the API docs here: https://harrispopgen.github.io/mushi/stubs/mushi.kSFS.html#mushi.kSFS.infer_eta

Does this help?

**Comment by RenzoTale88** [comment]
Hi @WSDeWitt thank you, yes I was following that, but I was wondering if there was a more direct guide, without the simulated data. No worries anyway, I'll just come back here and ask for support in case I get stuck at some point :) Thank you very much anyway!
